name: Deploy SakanoQR Payment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Debug repository structure
      - name: Debug repository structure
        run: ls -R

      # Step 3: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Terraform Init
        working-directory: infra/terraform  # Update to the correct path
        run: terraform init

      # Step 5: Plan Terraform changes
      - name: Terraform Plan
        working-directory: infra/terraform  # Update to the correct path
        run: terraform plan

      # Step 6: Apply Terraform changes
      - name: Terraform Apply
        working-directory: infra/terraform  # Update to the correct path
        run: terraform apply -auto-approve
