name: Deploy SakanoQR Payment

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1  # Set your AWS region
  TF_WORKING_DIR: infra/terraform  # Adjust if your Terraform is in a different folder

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write  # Needed for OIDC authentication with AWS

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Initialize Terraform
      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      # Plan Terraform changes
      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan

      # Apply Terraform changes
      - name: Terraform Apply
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -auto-approve

     
